# B站解析开关，单独开关，受「总开关」影响
bilibilitool: true

# B站解析提示，发送提示信息：“检测到B站链接，开始解析”
bilibilitip: true

# B站评论图，发送哔哩哔哩作品评论图
bilibilicommentsimg: true

# B站评论数量，设置接口返回的评论数量，范围1~20条
bilibilinumcomments: 5

# B站推送，开启后需重启；使用[#设置B站推送+用户UID]配置推送列表
bilibilipush: false

# B站推送日志，打开或关闭定时任务日志
bilibilipushlog: true

# B站推送设置权限，(all)所有人；(admin)群主和管理员；(owner)群主；(master)主人
bilibilipushGroup: master

# B站推送表达式
bilibilipushcron: '*/10 * * * *'