# 抖音解析开关，单独开关，受「总开关」影响
douyintool: true

# 抖音解析提示，发送提示信息：“检测到抖音链接，开始解析”
douyintip: true

# 抖音评论解析
comments: true

# 抖音评论数量，范围1~50条
numcomments: 5

# 发送抖音作品评论图
commentsimg: true

# 抖音推送，开启后需重启；使用[#设置抖音推送+抖音号]配置推送列表
douyinpush: false

# 抖音推送日志，打开或关闭定时任务日志
douyinpushlog: true

# 抖音推送设置权限，0: (all)所有人；1: (admin)群主和管理员；2: (owner)群主；3: (master)主人
douyinpushGroup: 3

# 抖音推送表达式
douyinpushcron: '*/10 * * * *'

# 图集BGM是否使用高清语音发送，高清语音「ios/PC」系统均无法播放，自行衡量开关（仅icqq）
sendHDrecord: true