# # 抖音推送列表
# douyin:
#   -
#     # 抖音用户（可不填，执行推送时会自动填上）
#     sec_uid: 
#     # 抖音号（必填）
#     short_id: 
#     # 推送群号和机器人账号，多个则使用逗号隔开（必填，例子：[12345678:87654321, 11451419:88888888]，群号就是11451419，机器人账号就是88888888）
#     group_id:
#       - 1145141919810:8888888888
#     # 这个博主的名字信息（可不填，执行推送时会自动填上）
#     remark: 

# # B站推送列表
# bilibili:
#   -
#     # B站用户（必填）
#     host_mid: 
#     # 推送群号和机器人账号，多个则使用逗号隔开（必填，例子：[12345678:87654321, 11451419:88888888]，群号就是11451419，机器人账号就是88888888）
#     group_id:
#       - 1145141919810:8888888888
#     # 这个UP主的名字信息（可不填，执行推送时会自动填上）
#     remark: 

# 抖音推送列表
douyin: 

# B站推送列表
bilibili: 