# 发送视频经本插件转换为base64格式后再发送，适合云崽与机器人不在同一网络环境下开启
sendbase64: false

# 视频上传拦截，开启后会根据解析的视频文件大小判断是否需要上传
usefilelimit: true

# 视频拦截阈值（填数字），视频文件大于该数值则不会上传 单位: MB，「视频文件上传限制」开启后才会生效
filelimit: 100

# 压缩视频，开启后会将视频文件压缩后再上传，适合上传大文件
compress: false

# 触发视频压缩的阈值，单位：MB。当文件大小超过该值时，才会压缩视频，「压缩视频」开启后才会生效
compresstrigger: 100

# 压缩后的值，若视频文件大小大于「触发视频压缩的阈值」的值，则会进行压缩至该值（±5%），「压缩视频」开启后才会生效
compressvalue: 50

# 使用文件上传，开启后会将视频文件上传到群文件中，私聊也行
usegroupfile: false

# 群文件上传阈值，当文件大小超过该值时将使用群文件上传，单位：MB，「使用群文件上传」开启后才会生效
groupfilevalue: 100
