asuijimanhua: true
cchuoyichuom: false
yifensuijimanghe: true
ssttoooc: true
seettuuplus: false
yuanmangheshen: true
sanciyuan: true
yunxiyuan: true
xiaofeifengkong: true
qlnc: false
lx: 0
one: false
two: false
three: false
four: false
five: false
six: false
seven: false
eight: false
nine: false
ten: false